// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXdsJbZMiE7QQWpKO0YWTXJJ2SmkyoL0',
    appId: '1:548441366511:android:a1bb8ef10e69f0d97ca01a',
    messagingSenderId: '548441366511',
    projectId: 'minichat-f4c70',
    storageBucket: 'minichat-f4c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Wv110cSUord1iO1uoUQgCIct80sF1Kk',
    appId: '1:548441366511:ios:19d808b9dc1550ae7ca01a',
    messagingSenderId: '548441366511',
    projectId: 'minichat-f4c70',
    storageBucket: 'minichat-f4c70.appspot.com',
    androidClientId: '548441366511-ie3l1a0dsetksr7npsqf9s7tnfdsup13.apps.googleusercontent.com',
    iosClientId: '548441366511-h4mjs88gqd428cl702nld5cqr0jlo9sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
